.TH S7C-CLI "1" "June 2016" "super7coin-cli 0.12"
.SH NAME
super7coin-cli \- a remote procedure call client for Super7Coin Core. 
.SH SYNOPSIS
super7coin-cli [options] <command> [params] \- Send command to Super7Coin Core. 
.TP
super7coin-cli [options] help \- Asks Super7Coin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the super7coin-cli program. super7coin-cli is an RPC client used to send commands to Super7Coin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBsuper7coind\fP, \fBsuper7coin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
